import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "" /* / */,

    // "",
    {
      text: "随笔打油诗",
      icon: "",
      prefix: "Poem/",
      children: "structure",
    },
    {
      text: "安全",
      icon: "shield-heart",
      collapsible: true,
      prefix: "Safety/",
      children: "structure",
    },
    {
      text: "算法",
      icon: "shield-heart",
      collapsible: true,
      prefix: "算法/",
      children: "structure",
    },
    {
      text: "低代码",
      icon: "laptop-code",
      collapsible: true,
      prefix: "LowCode/",
      children: "structure",
    },
    {
      text: "工程化相关",
      icon: "code-compare",
      collapsible: true,
      prefix: "CLI/",
      children: "structure",
    },
    {
      text: "小程序",
      icon: "comments",
      collapsible: true,
      prefix: "MiniProgram/",
      children: "structure",
    },

    {
      text: "杂库",
      icon: "warehouse",
      prefix: "Other/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Docker",
      icon: "linode",
      collapsible: true,
      prefix: "Docker/",
      children: "structure",
    },
    {
      text: "Node",
      icon: "node",
      prefix: "Node/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Vue",
      icon: "cat",
      prefix: "Vue/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Webpack",
      icon: "cubes",
      prefix: "Webpack",
      collapsible: true,
      children: "structure",
    },
    {
      text: "NestJS",
      icon: "code",
      prefix: "NestJS",
      collapsible: true,
      children: "structure",
    },
    {
      text: "GraphQL",
      icon: "project-diagram",
      prefix: "GraphQL",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Monorepo",
      icon: "menorah",
      prefix: "Monorepo",
      collapsible: true,
      children: "structure",
    },
    {
      text: "微前端",
      icon: "shapes",
      prefix: "微前端",
      collapsible: true,
      children: "structure",
    },
    {
      text: "CSS",
      icon: "css3",
      prefix: "CSS", 
      collapsible: true,
      children: "structure",
    },
    {
      text: "Web3",
      icon: "vector-square",
      prefix: "Web3", 
      collapsible: true,
      children: "structure",
    },
    {
      text: "碎碎念",
      icon: "theater-masks",
      prefix: "碎碎念/",
      children: "structure",
    },
    // "intro",
    // "slides",
  ],
});
